spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.3.42/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  jackson:
    default-property-inclusion: non_null
  freemarker:
    cache: false
    charset: utf-8
    content-type: text/html
    template-loader-path: classpath:/templates
    suffix: .ftl
  redis:
    host: 192.168.3.42
    port: 6379


#logging:
#  pattern:
#    console: "%d - %msg%n"
server:
  servlet:
    context-path: /sell
#  file: ./log/sell.

wechat:
  mpAppId: wxd41d41dce765881f
  mpAppSecret: a3e25a6e72e80c696656cbc3392a33c5
#  mchId:
#  mchKey:
#  keyPath: /var/xx/xx
#  notifyUrl: http://xxx/sell/pay/notify
mybatis:
  mapper-locations: classpath:mapper/*.xml
